import os
import subprocess
import re
from pathlib import Path
from git import Repo
from datetime import datetime
from github import Github
from config import GITHUB_TOKEN, REPO_PATH


def read_files(file_paths: list[str]) -> dict[str, str]:
    """Reads the content of target files."""
    content = {}
    for path in file_paths:
        try:
            with open(path, 'r', encoding='utf-8') as f:
                content[path] = f.read()
        except FileNotFoundError:
            content[path] = "" # Handle new file case
    return content

def write_files(files_dict: dict[str, str]) -> None:
    """Writes the generated code and tests to disk."""
    for path, content in files_dict.items():
        # Ensure directory exists
        os.makedirs(os.path.dirname(os.path.abspath(path)) or ".", exist_ok=True)
        with open(path, 'w', encoding='utf-8') as f:
            f.write(content)

def run_pytest(test_files: dict[str, str]) -> tuple[bool, str]:
    """Executes pytest in a subprocess and captures output."""
    test_paths = list(test_files.keys())
    if not test_paths:
        return True, "No test files to run."
    
    cmd = ["pytest"] + test_paths
    try:
        result = subprocess.run(
            cmd,
            cwd=REPO_PATH,
            capture_output=True,
            text=True
        )
        output = result.stdout
        if result.stderr:
            output += "\n--- STDERR ---\n" + result.stderr
        return result.returncode == 0, output
    except Exception as e:
        return False, f"Failed to run pytest: {str(e)}"

def extract_repo_name(repo: Repo) -> str:
    """Extracts owner/repo from git remote origin or TARGET_REPO_URL."""
    try:
        url = repo.remotes.origin.url
        # Match https://github.com/owner/repo.git or git@github.com:owner/repo.git
        match = re.search(r"github\.com[:/]([^/]+/[^/\.]+)", url)
        if match:
            return match.group(1)
    except Exception:
        pass
    
    from config import TARGET_REPO_URL
    if TARGET_REPO_URL:
        match = re.search(r"github\.com[:/]([^/]+/[^/\.]+)", TARGET_REPO_URL)
        if match:
            return match.group(1)
            
    return ""

def create_git_pr(branch_prefix="fix/agent-refactor") -> str:
    """Creates a new branch, commits changes, pushes to remote, and opens a PR."""
    if not GITHUB_TOKEN:
        return "Error: GITHUB_TOKEN is not set in environment or config."
        
    try:
        repo = Repo(REPO_PATH)
        timestamp = datetime.now().strftime("%Y%m%d%H%M%S")
        branch_name = f"{branch_prefix}-{timestamp}"
        
        if repo.is_dirty(untracked_files=True):
            # Create and checkout new branch
            new_branch = repo.create_head(branch_name)
            new_branch.checkout()
            
            # Add all changes
            repo.git.add(A=True)
            
            # Commit
            commit_msg = "Auto-generated changes by Self-Healing Agent"
            repo.index.commit(commit_msg)
            
            # Push to remote
            origin = repo.remotes.origin
            origin.push(branch_name)
            
            # Create PR using PyGithub
            repo_name = extract_repo_name(repo)
            if not repo_name:
                return f"Branch {branch_name} pushed, but could not determine repository name to create PR."
                
            g = Github(GITHUB_TOKEN)
            gh_repo = g.get_repo(repo_name)
            
            # Try to determine default branch
            default_branch = gh_repo.default_branch
            
            pr = gh_repo.create_pull(
                title=commit_msg,
                body="These changes were automatically generated by the Self-Healing Agent.",
                head=branch_name,
                base=default_branch
            )
            
            return pr.html_url
        else:
            return "No changes to commit."
            
    except Exception as e:
        print(f"Git or GitHub operation failed: {e}")
        return f"Error: {e}"
